<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign in</title>
</head>
<body>
    <form action="index.php?c=user&signin" method="post">
        <input type="text" placeholder="username:" name="username" id="username" required>
        <input type="password" placeholder="password:" name="password" id="password" required>
        <input type="email" placeholder="email:" name="email" id="email" required>
        <input type="submit" value="Registrarse" name="signin" id="signin">
    </form>
</body>
</html>