<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Añadir Producto</title>
</head>

<body>
    <form action="index.php?c=product" method="post" enctype="multipart/form-data">
        <input type="text" name="name" placeholder="Nombre:" required>
        <input type="text" name="description" placeholder="Descripción:" required>
        <input type="file" name="image" accept="image/*" required>
        <input type="number" name="stock" placeholder="Cantidad:" required>
        <input type="number" step="0.01" name="price" placeholder="Precio:" required>
        <input type="submit" name="addProduct" value="Añadir">
    </form>
</body>

</html>