<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="index.php?c=user&login" method="post">
        <input type="text" placeholder="username:" name="username" id="username" required>
        <input type="password" placeholder="password:" name="password" id="password" required>
        <input type="submit" value="Iniciar Sesión" name="login" id="login">
    </form>
</body>
</html>