<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search</title>
</head>

<body>
    <header>
        <a href="index.php">Home</a>
    </header>
    <h2>Buscar Cancion</h2>
    <form action="index.php?c=song" method="post">
        <input type="text" placeholder="Nombre de la cancion:" name="title" id="title">
        <input type="text" placeholder="Nombre del autor:" name="author" id="author">
        <input type="submit" value="Buscar" name="search">
    </form>
    <h2>Añadir Cancion</h2>
    <form action="index.php?c=song" method="post" enctype="multipart/form-data">
        <input type="text" placeholder="Nombre de la canción: " name="title" id="title">
        <input type="text" placeholder="Autor: " name="author" id="author">
        <input type="number" placeholder="Duración:" name="length" id="length">
        <input type='file' name='song' accept='audio/mp3'>
        <input type="submit" value="Añadir" name=" add">
    </form>
    <ul>
        <?php
        foreach ($Songs as $song) {
            echo "<li><strong>$song->title</strong></li>";
            echo "<form action='index.php?c=song' method='post'>
                        <input type='hidden' name='songId' value='$song->id'>
                        <input list='playlist' placeholder='Añadir a:' name='playlistId' />
                        <datalist id='playlist'>";
            foreach ($Playlists as $playlist) {
                echo "<option label='$playlist->title' value='$playlist->id'></option>";
            }
            echo "</datalist>
                <button type='submit' name='playlist'>Añadir</button>
                </form>";
        }
        echo "</li>";

        ?>
    </ul>
</body>

</html>