<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/public/css/loginView.css">
    <title>Inicio de Sesión</title>
</head>

<body>
    <h1>Iniciar Sesión</h1>
    <form action="index.php?c=user" method="POST">
        <label for="username">Nombre de Usuario:</label>
        <input type="text" id="username" name="username" required autocomplete="username"><br><br>

        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required autocomplete="current-password"><br><br>

        <input type="submit" name="inicio" value="Iniciar Sesión">
    </form>
</body>

</html>