<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Company</title>
</head>
<body>
    <form action="index.php?c=company&create" method="post">
        <input type="text" name="name" id="name" placeholder="Nombre:" required>
        <input type="text" name="nif" id="nif" placeholder="NIF:" required>
        <input type="text" name="address" id="address" placeholder="Direccion:" required>
        <input type="text" name="tutor" id="tutor" placeholder="Tutor" required>
        <input type="text" name="telephone" id="telephone" placeholder="Teléfono:" required>
        <input type="email" name="email" id="email" placeholder="Email:" required>
        <input type="submit" value="Añadir" name="add">
    </form>
</body>
</html>