<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List Company</title>
</head>
<body>
<a href="index.php">Home</a>
    <ul>
    <?php 
        foreach ($Companys as $company) {
            $nif = $company->getNif();
            $name = $company->getName();
            $address = $company->getAddress();
            echo "<li><strong>Nombre:</strong> <a href=index.php?c=company&id=$nif>$name</a> - $address - <a href=index.php?c=company&delete=$nif>Eliminar</a></li>";
        }
    ?>
    </ul>
</body>
</html>