<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Practices</title>
</head>
<body>
    <a href="index.php">Home</a>
    <form action="index.php?c=practice&search" method="post">
        <input type="text" name="name" >
        <input type="submit" value="Buscar">
    </form>
    <?php 
        foreach ($Practices as $practice) {
            $user = $practice->getUser();
            $user_id = $user->getId();
            $name = $user->getUsername();
            $practice_id = $practice->getId();

            echo "<li> <a href='index.php?c=practice&edit=$user_id'>Modificar Practicas de $name</a>";
            echo "</br><a href='index.php?c=practice&delete=$practice_id'>Eliminar Practicas de $name</a></li>";
        }
    ?>
   
</body>
</html>