<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="index.php?c=user" method="post">
        <input type="text" name="username" id="usernema" placeholder="Nombre de usuario:" required>
        <input type="password" name="password" id="password" placeholder="password" required>
        <input type="submit" value="Login" name="login">
        <input type="submit" value="Signin" name="signin">
    </form>
</body>
</html>