<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List</title>
</head>

<body>
    <?php
    if (isset($_SESSION['user'])) {
        echo "<a href='index.php?c=user&&close'>Cerrar</a>";
        echo "<h1>" . $_SESSION['user']->getUsername() . "</h1>";

        $admin = $_SESSION['user']->getType() === "admin";

        if ($admin) {
            echo "<a href='index.php?c=product'>Añadir producto</a></br>";
            echo "<a href='index.php?c=listUser'>Gestionar usuario</a></br>";
        } else {
            echo "<a href='index.php?c=cashOrder'>Carrito</a>";
        }
    }

    foreach ($products as $product) {
        // Declaración de variables
        $id = $product->getId();
        $name = $product->getName();
        $img = $product->getImage();
        $description = $product->getDescription();
        $stock = $product->getStock();
        $price = $product->getPrice();

        // Mostrar
        if ($stock > 0) {
            echo "<div>";
            echo "<img src='./public/img/$img' alt='Imagen de producto' width='100px'>";
            echo "<h3>$name</h3>";
            echo "<p><strong>$stock und</strong>  $price €</p>";
            echo "<p>$description</p>";
            if (isset($_SESSION['user']) && !$admin) {
                echo
                "<form action='index.php?c=cashOrder' method='post'>
                    <input type='hidden' name='id_product' value='$id'/>
                    <input type='hidden' name='name' value='$name'/>
                    <input type='hidden' name='price' value='$price'/>
                    <input id='amount$id' name='amount' type='range' min='1' max='$stock' value='1' step='1' />
                    <p>Value: <output id='value$id'></output></p>
                    <input type='submit' name='buy' value='Comprar'/>
                </form>
                <script>
                    const value$id = document.getElementById('value$id');
                    const input$id = document.getElementById('amount$id');
                    value$id.textContent = input$id.value;
                    input$id.addEventListener('input', (event) => {
                    value$id.textContent = event.target.value;
                    });
                </script>";
            }
        }
        echo "</div>";
    }


    ?>

</body>

</html>