<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List User</title>
</head>
<body>
    <?php
    $user = $_SESSION['user']->getUsername();
    echo "<h1>Pedidos</h1>";
    echo "<a href='index.php?user=$user'>home</a>";
    foreach ($cashOrders as $cashorder) {
        $id = $cashorder->getId();
        $status = $cashorder->getStatus();
        echo "
                <h3>$id</h3>
                <p>$status</p>
                <form action='index.php?c=listCashOrders&change=$id' method='post'>
                <select name='status' id='status'>
                    <option value='closed'>Cerrado</option>
                    <option value='paid'>Pagado</option>
                    <option value='sent'>Enviado</option>
                </select>
                <input type='submit' value='Cambiar'>
                </form>
        ";
    }    
    ?>
</body>
</html>