<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List User</title>
</head>
<body>
    <?php
    $user = $_SESSION['user']->getUsername();
    echo "<h1>Usuarios</h1>";
    echo "<a href='index.php?user=$user'>home</a>";
    foreach ($users as $user) {
        $name = $user->getUsername();
        $type = $user->getType();
        echo "<p><a href='index.php?c=listUser&change=$name'>$name</a>: $type</p>";
    }
    
    if (isset($_GET['change'])) {
        $username = $_GET['change'];
        $user = UserRepository::getUserByUsername($username);
        UserRepository::changeType($user);
        header("Location: index.php?c=listUser");
    }
    ?>
</body>
</html>