<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>

<body>
    <form action="index.php?c=user" method="post">
        <input type="text" name="username" placeholder="Username" id="username" required>
        <input type="password" name="password" placeholder="Password" id="password" required>

        <?php
        if (!isset($_SESSION['user'])) {
            echo "<input type='submit' name='login' value='Login'>";
        }
        if (isset($_SESSION['user']) && $_SESSION['user']->getType() === "admin") {
            echo "<select name='type' id='type' required>";
            echo "<option value='admin'>Admin</option>";
            echo "<option value='user'>User</option>";
            echo "</select>";
            echo "<input type='submit' name='signin' value='Sign in'>";
        }
        ?>

    </form>
</body>

</html>