<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php
    echo "<h2>" . $pl->getName() . "</h2>";

    foreach ($pl->getSongs() as $song) {

        echo serialize($song);
        echo $song->getTitle();
        echo '<audio src="public/mp3/' . $song->getMp3() . '" controls>
  Your browser does not support the <code>audio</code> element.
</audio><br>';
    }

    ?>
</body>

</html>