<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php $_GET['eachMovie']; ?></title>
</head>
<body>
    <?php

        $eachmovie = MovieRepository::getMoviesByTitle($_GET['eachMovie'])[0];
        echo "<h1>" . $eachmovie->getTitle() . "</h1>";
        $allComments = CommentRepository::getComments($eachmovie->getId() );
        $favoritos = FavoritesRepository::getAllFavoritesByMovieId($eachmovie->getId());
        foreach($allComments as $comment){
            echo "<div>";
            echo "<p><strong>". $comment->getUser(). " : </strong>". $comment->getComment(). "</p>" ;
            echo "</div>";
        }

        echo "<h2>Favoritos</h1>";
        
        foreach($favoritos as $favorito){
            echo "<p>". $favorito->getUser(). "</p>";
        }

    ?>
</body>
</html>