<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forum</title>
</head>
<body>
<header>
    <h1><?php echo $forum->name; ?></h1>
</header>

<?php
            foreach ($Matters as $matter) {
                echo "<li><a href='index.php?c=matter&id=" . $matter->id . "'>" . $matter->name . "</a></li>";
                $Responses = MatterRepository::getAllResponseByMatter($matter->id);
                    for ($i=0; $i < 2; $i++) { 
                        if ($i<count($Responses)) {
                            echo "<ul type='1'>
                            <li> " . $Responses[$i]->text . "</li>  
                            </ul>";
                        }
                    }
            }
        ?>
</body>
</html>