<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forum</title>
</head>
<body>
<header>
    <h1><?php echo $forum->name; ?></h1>
    <a href="index.php">Home</a>
    <?php
        if (isset($_SESSION['user'])) {
            echo "<form action='index.php?c=matter&add=$forum->id' method='post'>
                        <input type='text' name='matter' id='matter' placeholder='Nombre del tema:' required>
                        <input type='submit' value='Añadir' name='add' id='add'>
                    </form>";
        }
    ?>
</header>
<ul>
<?php
            foreach ($Matters as $matter) {
                echo "<li><a href='index.php?c=matter&id=" . $matter->id . "'>" . $matter->name . "</a></li>";
                if (isset($_SESSION['user']) && (UserRepository::getUserByNickName($_SESSION['user'])->type == 'admin')) {
                    echo "<form action='index.php?c=matter&status=$matter->id' method='post'>
                            <input type='hidden' value='$forum->id' name='forum'>
                            <input type='submit' value='$matter->status' name='status' id='status'>
                            <input type='submit' value='Delete' name='delete' id='delete'>
                        </form>";
                }
                $Responses = MatterRepository::getAllResponseByMatter($matter->id);
                    for ($i=0; $i < 2; $i++) { 
                        if ($i<count($Responses)) {
                            echo "<ul type='1'>
                            <li> " . $Responses[$i]->text . "</li>  
                            </ul>";
                        }
                    }
            }
        ?>
</ul>
</body>
</html>