<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List User</title>
</head>
<body>
    <header>
        <a href="index.php?">Home</a>
    </header>
    <ul>
    <?php
        foreach ($Users as $user) {
            echo "<li><strong>$user->nickname: </strong><a href='index.php?c=user&type=$user->nickname'>$user->type</a></li>";
        }
    ?>
    </ul>
</body>
</html>