<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="index.php?c=user" method="post">
        <input type="text" placeholder="nickname:" name="nickname" id="nickname" required>
        <input type="password" placeholder="password:" name="password" id="password" required>
        <input type="submit" value="Login" name="login" id="login">
    </form>
</body>
</html>