<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main</title>
</head>
<body>
    <header>
        <?php
            if (!isset($_SESSION['user'])) {
                echo '<a href="index.php?c=user&login">Iniciar Sesión</a>
                        <a href="index.php?c=user&signin">Registrarse</a>';
            }else {
                echo '<a href="index.php?c=user&close">Cerrar Sesión</a>';
            }

            if (isset($_SESSION['user']) && $user->type == 'admin') {
                echo '<a href="index.php?c=user&list">Listar Usuarios</a>';
            }
        ?>
        
    </header>

    <article>
        <ul>
        <?php
            foreach ($Forums as $forum) {
                if (isset($_SESSION['user']) || (!isset($_SESSION['user']) && $forum->public) ) {
                    echo "<li><a href='index.php?c=forum&id=" . $forum->id . "'>" . $forum->name . "</a></li>";
                    if (isset($_SESSION['user']) && $user->type == 'admin') {
                        echo "<a href='index.php?c=forum&public=$forum->id'></a>";
                    }
                    $Matters = ForumRepository::getMatterByForum($forum->id);
                    for ($i=0; $i < 2; $i++) { 
                        if ($i<count($Matters)) {
                            echo "<ul type='1'>
                            <li> " . $Matters[$i]->name . "</li>  
                            </ul>";
                        }
                    }
                    
                }
            }
                
        ?>
        
        </ul>
    </article>
</body>
</html>