<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main</title>
</head>
<body>
    <header>
        <?php
            if (!isset($_SESSION['user'])) {
                echo '<a href="index.php?c=user&login">Iniciar Sesión</a>
                        <a href="index.php?c=user&signin">Registrarse</a>';
            }else {
                echo '<a href="index.php?c=user&close">Cerrar Sesión</a>';
            }
        ?>
        
    </header>

    <article>
        <ul>
        <?php
            foreach ($Forums as $forum) {
                echo '<li>' . $forum->name . '</li>';
            }
        ?>
        </ul>
    </article>
</body>
</html>