<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Matter</title>
</head>
<body>

<header>
    <h1><?php echo $matter->name  ?></h1>
</header>
<?php
            foreach ($Responses as $response) {
                echo "<li><strong>". $response->user . ": </strong>" . $response->text . "</li>";
            }
        ?>
</body>
</html>