<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="index.php?c=user" method="post" enctype="multipart/form-data">
        <input type="file" name="image" accept="image/*" required>
        <input type="email" placeholder="email:" name="email" id="email" required>
        <input type="text" placeholder="nickname:" name="nickname" id="nickname" required>
        <input type="password" placeholder="password:" name="password" id="password" required>
        <input type="submit" value="signin" name="signin" id="signin">
    </form>
</body>
</html>